# Generated by Django 4.2.7 on 2024-08-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('topspeed', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('insurance', models.BooleanField(default=False)),
                ('seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
        ),
    ]
