# Generated by Django 4.2.7 on 2024-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0002_carrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='number_plate',
            field=models.CharField(default=9090, max_length=50),
            preserve_default=False,
        ),
    ]
